[HISversion]
version = "2.0.0 (2017-05-09)"

[logger]
mode = "debug"
#logFileName = "/tmp/his.log"

[server]
#httpHostIp = "10.194.18.46"  
httpHostPort = 8000
readTimeout  = 5000000000 # in nanoseconds
writeTimeout = 10000000000 # in nanoseconds
tls          = true

[chaincode]
chainCodePath     = "github.com/consentv2"
chainCodeVersion  = "v0"
chainCodeID       = "consentv2"
chainID           = "testchannel"
providerName      = "SW"

[path]
repo              = "/opt/gopath/src/github.com/pascallimeux/his/fixtures"
statStorePath     = "/opt/gopath/src/github.com/pascallimeux/his/fixtures/enroll_user"
networkConfigFile = "/opt/gopath/src/github.com/pascallimeux/his/fixtures/config/config_dev.yaml"
channelConfigFile = "/opt/gopath/src/github.com/pascallimeux/his/fixtures/channel/testchannel.tx"

[admin]
adminUsername     = "admin"
adminPwd          = "adminpw"