[HISversion]
version = "2.0.0 (2017-05-09)"

[logger]
mode = "debug"
logFileName = "/var/log/his/his.log"

[server]
#httpHostIp = "10.194.18.46"  
httpHostPort = 8000
readTimeout  = 5000000000 # in nanoseconds
writeTimeout = 10000000000 # in nanoseconds
tls          = false

[chaincode]
chainCodePath     = "github.com/consentv3"
chainCodeVersion  = "v0"
chainCodeID       = "consentv3"
chainID           = "testchannel"
providerName      = "SW"

[path]
repo              = "/var/his/fixtures"
statStorePath     = "/var/his/fixtures/enroll_user"
networkConfigFile = "/var/his/fixtures/config/config_prod.yaml"
channelConfigFile = "/var/his/fixtures/channel/testchannel.tx"

[admin]
authMode          = "false"
adminUsername     = "admin"
adminPwd          = "adminpw"