[HISversion]
version = "2.0.0 (2017-05-09)"

[logger]
mode = "error"

[server]
#httpHostIp = "10.194.18.46"
httpHostPort = 8000
readTimeout  = 5000000000 # in nanoseconds
writeTimeout = 10000000000 # in nanoseconds
tls          = false

[chaincode]
chainCodePath     = "github.com/consentv3"
chainCodeVersion  = "v0"
chainCodeID       = "consentv3test"
chainID           = "testchannel"
providerName      = "SW"

[path]
repo              = "/opt/gopath/src/github.com/pascallimeux/his/his/fixtures"
statStorePath     = "/opt/gopath/src/github.com/pascallimeux/his/his/fixtures/enroll_user"
networkConfigFile = "/opt/gopath/src/github.com/pascallimeux/his/his/fixtures/config/config_dev.yaml"
channelConfigFile = "/opt/gopath/src/github.com/pascallimeux/his/his/fixtures/channel/testchannel.tx"

[admin]
authMode          = false
adminUsername     = "admin"
adminPwd          = "adminpw"