package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/pascallimeux/his/restapi/operations/consents"
	"github.com/pascallimeux/his/restapi/operations/version"
)

// NewHisAPI creates a new His instance
func NewHisAPI(spec *loads.Document) *HisAPI {
	return &HisAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		ConsentsCreateConsentHandler: consents.CreateConsentHandlerFunc(func(params consents.CreateConsentParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsCreateConsent has not yet been implemented")
		}),
		ConsentsDeleteConsentHandler: consents.DeleteConsentHandlerFunc(func(params consents.DeleteConsentParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsDeleteConsent has not yet been implemented")
		}),
		ConsentsDeleteConsentsHandler: consents.DeleteConsentsHandlerFunc(func(params consents.DeleteConsentsParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsDeleteConsents has not yet been implemented")
		}),
		ConsentsGetConsentHandler: consents.GetConsentHandlerFunc(func(params consents.GetConsentParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsGetConsent has not yet been implemented")
		}),
		ConsentsGetConsentsHandler: consents.GetConsentsHandlerFunc(func(params consents.GetConsentsParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsGetConsents has not yet been implemented")
		}),
		ConsentsGetConsents4ConsumerHandler: consents.GetConsents4ConsumerHandlerFunc(func(params consents.GetConsents4ConsumerParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsGetConsents4Consumer has not yet been implemented")
		}),
		ConsentsGetConsents4ConsumerOwnerHandler: consents.GetConsents4ConsumerOwnerHandlerFunc(func(params consents.GetConsents4ConsumerOwnerParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsGetConsents4ConsumerOwner has not yet been implemented")
		}),
		ConsentsGetConsents4OwnerHandler: consents.GetConsents4OwnerHandlerFunc(func(params consents.GetConsents4OwnerParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsGetConsents4Owner has not yet been implemented")
		}),
		VersionGetVersionHandler: version.GetVersionHandlerFunc(func(params version.GetVersionParams) middleware.Responder {
			return middleware.NotImplemented("operation VersionGetVersion has not yet been implemented")
		}),
		ConsentsIsConsentHandler: consents.IsConsentHandlerFunc(func(params consents.IsConsentParams) middleware.Responder {
			return middleware.NotImplemented("operation ConsentsIsConsent has not yet been implemented")
		}),
	}
}

/*HisAPI Hyperledger Interface Server */
type HisAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ConsentsCreateConsentHandler sets the operation handler for the create consent operation
	ConsentsCreateConsentHandler consents.CreateConsentHandler
	// ConsentsDeleteConsentHandler sets the operation handler for the delete consent operation
	ConsentsDeleteConsentHandler consents.DeleteConsentHandler
	// ConsentsDeleteConsentsHandler sets the operation handler for the delete consents operation
	ConsentsDeleteConsentsHandler consents.DeleteConsentsHandler
	// ConsentsGetConsentHandler sets the operation handler for the get consent operation
	ConsentsGetConsentHandler consents.GetConsentHandler
	// ConsentsGetConsentsHandler sets the operation handler for the get consents operation
	ConsentsGetConsentsHandler consents.GetConsentsHandler
	// ConsentsGetConsents4ConsumerHandler sets the operation handler for the get consents4 consumer operation
	ConsentsGetConsents4ConsumerHandler consents.GetConsents4ConsumerHandler
	// ConsentsGetConsents4ConsumerOwnerHandler sets the operation handler for the get consents4 consumer owner operation
	ConsentsGetConsents4ConsumerOwnerHandler consents.GetConsents4ConsumerOwnerHandler
	// ConsentsGetConsents4OwnerHandler sets the operation handler for the get consents4 owner operation
	ConsentsGetConsents4OwnerHandler consents.GetConsents4OwnerHandler
	// VersionGetVersionHandler sets the operation handler for the get version operation
	VersionGetVersionHandler version.GetVersionHandler
	// ConsentsIsConsentHandler sets the operation handler for the is consent operation
	ConsentsIsConsentHandler consents.IsConsentHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *HisAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *HisAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *HisAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *HisAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *HisAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *HisAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *HisAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the HisAPI
func (o *HisAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ConsentsCreateConsentHandler == nil {
		unregistered = append(unregistered, "consents.CreateConsentHandler")
	}

	if o.ConsentsDeleteConsentHandler == nil {
		unregistered = append(unregistered, "consents.DeleteConsentHandler")
	}

	if o.ConsentsDeleteConsentsHandler == nil {
		unregistered = append(unregistered, "consents.DeleteConsentsHandler")
	}

	if o.ConsentsGetConsentHandler == nil {
		unregistered = append(unregistered, "consents.GetConsentHandler")
	}

	if o.ConsentsGetConsentsHandler == nil {
		unregistered = append(unregistered, "consents.GetConsentsHandler")
	}

	if o.ConsentsGetConsents4ConsumerHandler == nil {
		unregistered = append(unregistered, "consents.GetConsents4ConsumerHandler")
	}

	if o.ConsentsGetConsents4ConsumerOwnerHandler == nil {
		unregistered = append(unregistered, "consents.GetConsents4ConsumerOwnerHandler")
	}

	if o.ConsentsGetConsents4OwnerHandler == nil {
		unregistered = append(unregistered, "consents.GetConsents4OwnerHandler")
	}

	if o.VersionGetVersionHandler == nil {
		unregistered = append(unregistered, "version.GetVersionHandler")
	}

	if o.ConsentsIsConsentHandler == nil {
		unregistered = append(unregistered, "consents.IsConsentHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *HisAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *HisAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *HisAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *HisAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *HisAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the his API
func (o *HisAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *HisAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/his/v0/api/app/{appid}/consents"] = consents.NewCreateConsent(o.context, o.ConsentsCreateConsentHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/his/v0/api/app/{appid}/consents/{consentid}"] = consents.NewDeleteConsent(o.context, o.ConsentsDeleteConsentHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/his/v0/api/app/{appid}/consents"] = consents.NewDeleteConsents(o.context, o.ConsentsDeleteConsentsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/his/v0/api/app/{appid}/consents/{consentid}"] = consents.NewGetConsent(o.context, o.ConsentsGetConsentHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/his/v0/api/app/{appid}/consents"] = consents.NewGetConsents(o.context, o.ConsentsGetConsentsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/his/v0/api/app/{appid}/consumer/{consumerid}/consents"] = consents.NewGetConsents4Consumer(o.context, o.ConsentsGetConsents4ConsumerHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/his/v0/api/app/{appid}/consumer/{consumerid}/owner/{ownerid}/consents"] = consents.NewGetConsents4ConsumerOwner(o.context, o.ConsentsGetConsents4ConsumerOwnerHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/his/v0/api/app/{appid}/owner/{ownerid}/consents"] = consents.NewGetConsents4Owner(o.context, o.ConsentsGetConsents4OwnerHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/ocms/v3/api/version"] = version.NewGetVersion(o.context, o.VersionGetVersionHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/his/v0/api/app/{appid}/isconsent"] = consents.NewIsConsent(o.context, o.ConsentsIsConsentHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *HisAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *HisAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
