package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/pascallimeux/his/models"
)

// NewCreateConsentParams creates a new CreateConsentParams object
// with the default values initialized.
func NewCreateConsentParams() CreateConsentParams {
	var ()
	return CreateConsentParams{}
}

// CreateConsentParams contains all the bound params for the create consent operation
// typically these are obtained from a http.Request
//
// swagger:parameters createConsent
type CreateConsentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The application ID to submit.
	  Required: true
	  In: path
	*/
	Appid string
	/*The consent to submit.
	  Required: true
	  In: body
	*/
	Consent *models.Consent
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateConsentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rAppid, rhkAppid, _ := route.Params.GetOK("appid")
	if err := o.bindAppid(rAppid, rhkAppid, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Consent
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("consent", "body"))
			} else {
				res = append(res, errors.NewParseError("consent", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Consent = &body
			}
		}

	} else {
		res = append(res, errors.Required("consent", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateConsentParams) bindAppid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Appid = raw

	return nil
}
