package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
)

// DeleteConsentsNoContentCode is the HTTP code returned for type DeleteConsentsNoContent
const DeleteConsentsNoContentCode int = 204

/*DeleteConsentsNoContent no content

swagger:response deleteConsentsNoContent
*/
type DeleteConsentsNoContent struct {
	/*
	  Required: true
	*/
	Nocontent string `json:"nocontent"`
}

// NewDeleteConsentsNoContent creates DeleteConsentsNoContent with default headers values
func NewDeleteConsentsNoContent() *DeleteConsentsNoContent {
	return &DeleteConsentsNoContent{}
}

// WithNocontent adds the nocontent to the delete consents no content response
func (o *DeleteConsentsNoContent) WithNocontent(nocontent string) *DeleteConsentsNoContent {
	o.Nocontent = nocontent
	return o
}

// SetNocontent sets the nocontent to the delete consents no content response
func (o *DeleteConsentsNoContent) SetNocontent(nocontent string) {
	o.Nocontent = nocontent
}

// WriteResponse to the client
func (o *DeleteConsentsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header nocontent

	nocontent := o.Nocontent
	if nocontent != "" {
		rw.Header().Set("nocontent", nocontent)
	}

	rw.WriteHeader(204)
}

/*DeleteConsentsDefault Genric error for API

swagger:response deleteConsentsDefault
*/
type DeleteConsentsDefault struct {
	_statusCode int
	/*in: path
	  Required: true
	*/
	Code int64 `json:"code"`
	/*
	  Required: true
	*/
	Message string `json:"message"`
}

// NewDeleteConsentsDefault creates DeleteConsentsDefault with default headers values
func NewDeleteConsentsDefault(code int) *DeleteConsentsDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteConsentsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete consents default response
func (o *DeleteConsentsDefault) WithStatusCode(code int) *DeleteConsentsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete consents default response
func (o *DeleteConsentsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the delete consents default response
func (o *DeleteConsentsDefault) WithCode(code int64) *DeleteConsentsDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the delete consents default response
func (o *DeleteConsentsDefault) SetCode(code int64) {
	o.Code = code
}

// WithMessage adds the message to the delete consents default response
func (o *DeleteConsentsDefault) WithMessage(message string) *DeleteConsentsDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the delete consents default response
func (o *DeleteConsentsDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *DeleteConsentsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header code

	code := swag.FormatInt64(o.Code)
	if code != "" {
		rw.Header().Set("code", code)
	}

	// response header message

	message := o.Message
	if message != "" {
		rw.Header().Set("message", message)
	}

	rw.WriteHeader(o._statusCode)
}
