package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
)

// DeleteConsentNoContentCode is the HTTP code returned for type DeleteConsentNoContent
const DeleteConsentNoContentCode int = 204

/*DeleteConsentNoContent no content

swagger:response deleteConsentNoContent
*/
type DeleteConsentNoContent struct {
	/*
	  Required: true
	*/
	Nocontent string `json:"nocontent"`
}

// NewDeleteConsentNoContent creates DeleteConsentNoContent with default headers values
func NewDeleteConsentNoContent() *DeleteConsentNoContent {
	return &DeleteConsentNoContent{}
}

// WithNocontent adds the nocontent to the delete consent no content response
func (o *DeleteConsentNoContent) WithNocontent(nocontent string) *DeleteConsentNoContent {
	o.Nocontent = nocontent
	return o
}

// SetNocontent sets the nocontent to the delete consent no content response
func (o *DeleteConsentNoContent) SetNocontent(nocontent string) {
	o.Nocontent = nocontent
}

// WriteResponse to the client
func (o *DeleteConsentNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header nocontent

	nocontent := o.Nocontent
	if nocontent != "" {
		rw.Header().Set("nocontent", nocontent)
	}

	rw.WriteHeader(204)
}

/*DeleteConsentDefault Genric error for API

swagger:response deleteConsentDefault
*/
type DeleteConsentDefault struct {
	_statusCode int
	/*in: path
	  Required: true
	*/
	Code int64 `json:"code"`
	/*
	  Required: true
	*/
	Message string `json:"message"`
}

// NewDeleteConsentDefault creates DeleteConsentDefault with default headers values
func NewDeleteConsentDefault(code int) *DeleteConsentDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteConsentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete consent default response
func (o *DeleteConsentDefault) WithStatusCode(code int) *DeleteConsentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete consent default response
func (o *DeleteConsentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the delete consent default response
func (o *DeleteConsentDefault) WithCode(code int64) *DeleteConsentDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the delete consent default response
func (o *DeleteConsentDefault) SetCode(code int64) {
	o.Code = code
}

// WithMessage adds the message to the delete consent default response
func (o *DeleteConsentDefault) WithMessage(message string) *DeleteConsentDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the delete consent default response
func (o *DeleteConsentDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *DeleteConsentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header code

	code := swag.FormatInt64(o.Code)
	if code != "" {
		rw.Header().Set("code", code)
	}

	// response header message

	message := o.Message
	if message != "" {
		rw.Header().Set("message", message)
	}

	rw.WriteHeader(o._statusCode)
}
