package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/pascallimeux/his/models"
)

// GetConsentsOKCode is the HTTP code returned for type GetConsentsOK
const GetConsentsOKCode int = 200

/*GetConsentsOK consent

swagger:response getConsentsOK
*/
type GetConsentsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Consent `json:"body,omitempty"`
}

// NewGetConsentsOK creates GetConsentsOK with default headers values
func NewGetConsentsOK() *GetConsentsOK {
	return &GetConsentsOK{}
}

// WithPayload adds the payload to the get consents o k response
func (o *GetConsentsOK) WithPayload(payload []*models.Consent) *GetConsentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get consents o k response
func (o *GetConsentsOK) SetPayload(payload []*models.Consent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConsentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Consent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetConsentsDefault Genric error for API

swagger:response getConsentsDefault
*/
type GetConsentsDefault struct {
	_statusCode int
	/*in: path
	  Required: true
	*/
	Code int64 `json:"code"`
	/*
	  Required: true
	*/
	Message string `json:"message"`
}

// NewGetConsentsDefault creates GetConsentsDefault with default headers values
func NewGetConsentsDefault(code int) *GetConsentsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConsentsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get consents default response
func (o *GetConsentsDefault) WithStatusCode(code int) *GetConsentsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get consents default response
func (o *GetConsentsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the get consents default response
func (o *GetConsentsDefault) WithCode(code int64) *GetConsentsDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the get consents default response
func (o *GetConsentsDefault) SetCode(code int64) {
	o.Code = code
}

// WithMessage adds the message to the get consents default response
func (o *GetConsentsDefault) WithMessage(message string) *GetConsentsDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the get consents default response
func (o *GetConsentsDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *GetConsentsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header code

	code := swag.FormatInt64(o.Code)
	if code != "" {
		rw.Header().Set("code", code)
	}

	// response header message

	message := o.Message
	if message != "" {
		rw.Header().Set("message", message)
	}

	rw.WriteHeader(o._statusCode)
}
