package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/pascallimeux/his/models"
)

// GetConsents4ConsumerOwnerOKCode is the HTTP code returned for type GetConsents4ConsumerOwnerOK
const GetConsents4ConsumerOwnerOKCode int = 200

/*GetConsents4ConsumerOwnerOK consent

swagger:response getConsents4ConsumerOwnerOK
*/
type GetConsents4ConsumerOwnerOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Consent `json:"body,omitempty"`
}

// NewGetConsents4ConsumerOwnerOK creates GetConsents4ConsumerOwnerOK with default headers values
func NewGetConsents4ConsumerOwnerOK() *GetConsents4ConsumerOwnerOK {
	return &GetConsents4ConsumerOwnerOK{}
}

// WithPayload adds the payload to the get consents4 consumer owner o k response
func (o *GetConsents4ConsumerOwnerOK) WithPayload(payload []*models.Consent) *GetConsents4ConsumerOwnerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get consents4 consumer owner o k response
func (o *GetConsents4ConsumerOwnerOK) SetPayload(payload []*models.Consent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConsents4ConsumerOwnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Consent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetConsents4ConsumerOwnerDefault Genric error for API

swagger:response getConsents4ConsumerOwnerDefault
*/
type GetConsents4ConsumerOwnerDefault struct {
	_statusCode int
	/*in: path
	  Required: true
	*/
	Code int64 `json:"code"`
	/*
	  Required: true
	*/
	Message string `json:"message"`
}

// NewGetConsents4ConsumerOwnerDefault creates GetConsents4ConsumerOwnerDefault with default headers values
func NewGetConsents4ConsumerOwnerDefault(code int) *GetConsents4ConsumerOwnerDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConsents4ConsumerOwnerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get consents4 consumer owner default response
func (o *GetConsents4ConsumerOwnerDefault) WithStatusCode(code int) *GetConsents4ConsumerOwnerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get consents4 consumer owner default response
func (o *GetConsents4ConsumerOwnerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the get consents4 consumer owner default response
func (o *GetConsents4ConsumerOwnerDefault) WithCode(code int64) *GetConsents4ConsumerOwnerDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the get consents4 consumer owner default response
func (o *GetConsents4ConsumerOwnerDefault) SetCode(code int64) {
	o.Code = code
}

// WithMessage adds the message to the get consents4 consumer owner default response
func (o *GetConsents4ConsumerOwnerDefault) WithMessage(message string) *GetConsents4ConsumerOwnerDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the get consents4 consumer owner default response
func (o *GetConsents4ConsumerOwnerDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *GetConsents4ConsumerOwnerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header code

	code := swag.FormatInt64(o.Code)
	if code != "" {
		rw.Header().Set("code", code)
	}

	// response header message

	message := o.Message
	if message != "" {
		rw.Header().Set("message", message)
	}

	rw.WriteHeader(o._statusCode)
}
