package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetConsents4OwnerURL generates an URL for the get consents4 owner operation
type GetConsents4OwnerURL struct {
	Appid   string
	Ownerid string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetConsents4OwnerURL) WithBasePath(bp string) *GetConsents4OwnerURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetConsents4OwnerURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetConsents4OwnerURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/his/v0/api/app/{appid}/owner/{ownerid}/consents"

	appid := o.Appid
	if appid != "" {
		_path = strings.Replace(_path, "{appid}", appid, -1)
	} else {
		return nil, errors.New("Appid is required on GetConsents4OwnerURL")
	}
	ownerid := o.Ownerid
	if ownerid != "" {
		_path = strings.Replace(_path, "{ownerid}", ownerid, -1)
	} else {
		return nil, errors.New("Ownerid is required on GetConsents4OwnerURL")
	}
	_basePath := o._basePath
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetConsents4OwnerURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetConsents4OwnerURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetConsents4OwnerURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetConsents4OwnerURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetConsents4OwnerURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetConsents4OwnerURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
