package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/pascallimeux/his/models"
)

// GetConsents4OwnerOKCode is the HTTP code returned for type GetConsents4OwnerOK
const GetConsents4OwnerOKCode int = 200

/*GetConsents4OwnerOK consent

swagger:response getConsents4OwnerOK
*/
type GetConsents4OwnerOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Consent `json:"body,omitempty"`
}

// NewGetConsents4OwnerOK creates GetConsents4OwnerOK with default headers values
func NewGetConsents4OwnerOK() *GetConsents4OwnerOK {
	return &GetConsents4OwnerOK{}
}

// WithPayload adds the payload to the get consents4 owner o k response
func (o *GetConsents4OwnerOK) WithPayload(payload []*models.Consent) *GetConsents4OwnerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get consents4 owner o k response
func (o *GetConsents4OwnerOK) SetPayload(payload []*models.Consent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConsents4OwnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Consent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetConsents4OwnerDefault Genric error for API

swagger:response getConsents4OwnerDefault
*/
type GetConsents4OwnerDefault struct {
	_statusCode int
	/*in: path
	  Required: true
	*/
	Code int64 `json:"code"`
	/*
	  Required: true
	*/
	Message string `json:"message"`
}

// NewGetConsents4OwnerDefault creates GetConsents4OwnerDefault with default headers values
func NewGetConsents4OwnerDefault(code int) *GetConsents4OwnerDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConsents4OwnerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get consents4 owner default response
func (o *GetConsents4OwnerDefault) WithStatusCode(code int) *GetConsents4OwnerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get consents4 owner default response
func (o *GetConsents4OwnerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the get consents4 owner default response
func (o *GetConsents4OwnerDefault) WithCode(code int64) *GetConsents4OwnerDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the get consents4 owner default response
func (o *GetConsents4OwnerDefault) SetCode(code int64) {
	o.Code = code
}

// WithMessage adds the message to the get consents4 owner default response
func (o *GetConsents4OwnerDefault) WithMessage(message string) *GetConsents4OwnerDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the get consents4 owner default response
func (o *GetConsents4OwnerDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *GetConsents4OwnerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header code

	code := swag.FormatInt64(o.Code)
	if code != "" {
		rw.Header().Set("code", code)
	}

	// response header message

	message := o.Message
	if message != "" {
		rw.Header().Set("message", message)
	}

	rw.WriteHeader(o._statusCode)
}
