package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/pascallimeux/his/models"
)

// GetConsents4ConsumerOKCode is the HTTP code returned for type GetConsents4ConsumerOK
const GetConsents4ConsumerOKCode int = 200

/*GetConsents4ConsumerOK consent

swagger:response getConsents4ConsumerOK
*/
type GetConsents4ConsumerOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Consent `json:"body,omitempty"`
}

// NewGetConsents4ConsumerOK creates GetConsents4ConsumerOK with default headers values
func NewGetConsents4ConsumerOK() *GetConsents4ConsumerOK {
	return &GetConsents4ConsumerOK{}
}

// WithPayload adds the payload to the get consents4 consumer o k response
func (o *GetConsents4ConsumerOK) WithPayload(payload []*models.Consent) *GetConsents4ConsumerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get consents4 consumer o k response
func (o *GetConsents4ConsumerOK) SetPayload(payload []*models.Consent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConsents4ConsumerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Consent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetConsents4ConsumerDefault Genric error for API

swagger:response getConsents4ConsumerDefault
*/
type GetConsents4ConsumerDefault struct {
	_statusCode int
	/*in: path
	  Required: true
	*/
	Code int64 `json:"code"`
	/*
	  Required: true
	*/
	Message string `json:"message"`
}

// NewGetConsents4ConsumerDefault creates GetConsents4ConsumerDefault with default headers values
func NewGetConsents4ConsumerDefault(code int) *GetConsents4ConsumerDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConsents4ConsumerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get consents4 consumer default response
func (o *GetConsents4ConsumerDefault) WithStatusCode(code int) *GetConsents4ConsumerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get consents4 consumer default response
func (o *GetConsents4ConsumerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the get consents4 consumer default response
func (o *GetConsents4ConsumerDefault) WithCode(code int64) *GetConsents4ConsumerDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the get consents4 consumer default response
func (o *GetConsents4ConsumerDefault) SetCode(code int64) {
	o.Code = code
}

// WithMessage adds the message to the get consents4 consumer default response
func (o *GetConsents4ConsumerDefault) WithMessage(message string) *GetConsents4ConsumerDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the get consents4 consumer default response
func (o *GetConsents4ConsumerDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *GetConsents4ConsumerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header code

	code := swag.FormatInt64(o.Code)
	if code != "" {
		rw.Header().Set("code", code)
	}

	// response header message

	message := o.Message
	if message != "" {
		rw.Header().Set("message", message)
	}

	rw.WriteHeader(o._statusCode)
}
