package consents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetConsents4ConsumerHandlerFunc turns a function with the right signature into a get consents4 consumer handler
type GetConsents4ConsumerHandlerFunc func(GetConsents4ConsumerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConsents4ConsumerHandlerFunc) Handle(params GetConsents4ConsumerParams) middleware.Responder {
	return fn(params)
}

// GetConsents4ConsumerHandler interface for that can handle valid get consents4 consumer params
type GetConsents4ConsumerHandler interface {
	Handle(GetConsents4ConsumerParams) middleware.Responder
}

// NewGetConsents4Consumer creates a new http.Handler for the get consents4 consumer operation
func NewGetConsents4Consumer(ctx *middleware.Context, handler GetConsents4ConsumerHandler) *GetConsents4Consumer {
	return &GetConsents4Consumer{Context: ctx, Handler: handler}
}

/*GetConsents4Consumer swagger:route GET /his/v0/api/app/{appid}/consumer/{consumerid}/consents consents getConsents4Consumer

GetConsents4Consumer get consents4 consumer API

*/
type GetConsents4Consumer struct {
	Context *middleware.Context
	Handler GetConsents4ConsumerHandler
}

func (o *GetConsents4Consumer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetConsents4ConsumerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
